// Generated by CoffeeScript 1.11.1
(function() {
  var NodeRender;

  NodeRender = (function() {
    function NodeRender() {}

    NodeRender.prototype.html = function(node) {
      var ul;
      ul = document.createElement('ul');
      this.htmlR(node, ul);
      return ul;
    };

    NodeRender.prototype.htmlR = function(node, parentElement) {
      var child, i, len, nodeHtml, ref, results;
      nodeHtml = new NodeHtml(node, parentElement);
      ref = node.children;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        child = ref[i];
        results.push(this.htmlR(child, nodeHtml.ul));
      }
      return results;
    };

    return NodeRender;

  })();

  window.NodeRender = NodeRender;

}).call(this);

//# sourceMappingURL=NodeRender.js.map
