// Generated by CoffeeScript 1.11.1
(function() {
  window.NodeStorage = {
    set: function(id, state) {
      return localStorage.setItem(id, state);
    },
    get: function(id) {
      var v;
      v = localStorage.getItem(id);
      if (v === null) {
        return null;
      } else {
        return !!parseInt(v);
      }
    }
  };

  window.NodeStorage = NodeStorage;

}).call(this);

//# sourceMappingURL=NodeStorage.js.map
