// Generated by CoffeeScript 1.11.1
(function() {
  var Node;

  Node = (function() {
    function Node(tree, data, parentNode) {
      this.tree = tree;
      this.data = data;
      this.parentNode = parentNode;
      if (this.data.opened === void 0) {
        this.data.opened = true;
      }
      this.children = [];
      if (this.data.id) {
        this.id = this.data.id;
      } else {
        Node.lastId++;
        this.id = Node.lastId;
      }
    }

    Node.prototype.getData = function() {
      var o;
      o = {
        name: this.data.name,
        id: this.id
      };
      if (!this.data.opened) {
        o.opened = false;
      }
      return o;
    };

    Node.prototype.getOpened = function() {
      return this.data.opened;
    };

    Node.prototype.deleteChild = function(id) {
      var child, i, index, j, len, ref;
      if (!this.children.length) {
        return;
      }
      index = -1;
      ref = this.children;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        child = ref[i];
        if (child.id === id) {
          index = i;
        }
      }
      console.log(index);
      if (index > -1) {
        return this.children.splice(index, 1);
      }
    };

    return Node;

  })();

  Node.lastId = 0;

  window.Node = Node;

}).call(this);

//# sourceMappingURL=Node.js.map
