// Generated by CoffeeScript 1.11.1
(function() {
  var Tree;

  Tree = (function() {
    function Tree(items, parent) {
      this.parent = parent || document.getElementsByTagName('body')[0];
      if (items) {
        this.load(items);
      }
    }

    Tree.prototype.load = function(items) {
      this.nodes = new TreeLoad(this).load(items);
      return this.root = this.nodes[0];
    };

    Tree.prototype.html = function() {
      this.parent.innerHTML = '';
      return this.parent.appendChild(new NodeRender().html(this.root));
    };

    Tree.prototype.json = function() {
      return JSON.stringify([this.jsonR(this.root)]);
    };

    Tree.prototype.jsonR = function(node) {
      var _node, i, json, len, ref;
      json = node.getData();
      if (node.children.length) {
        json.children = [];
        ref = node.children;
        for (i = 0, len = ref.length; i < len; i++) {
          _node = ref[i];
          json.children.push(this.jsonR(_node));
        }
      }
      return json;
    };

    Tree.prototype.onChange = null;

    Tree.prototype.fireChangeEvent = function() {
      if (this.onChange) {
        return this.onChange();
      }
    };

    return Tree;

  })();

  window.Tree = Tree;

}).call(this);

//# sourceMappingURL=Tree.js.map
