// Generated by CoffeeScript 1.11.1
(function() {
  var TreeLoad;

  TreeLoad = (function() {
    function TreeLoad(tree) {
      this.tree = tree;
    }

    TreeLoad.prototype.load = function(items) {
      var i, item, len, node, nodes;
      nodes = [];
      for (i = 0, len = items.length; i < len; i++) {
        item = items[i];
        node = new Node(this.tree, item);
        nodes.push(node);
        if (item.children) {
          this.loadR(item.children, node);
        }
      }
      return nodes;
    };

    TreeLoad.prototype.loadR = function(items, parentNode) {
      var i, item, len, node, results;
      results = [];
      for (i = 0, len = items.length; i < len; i++) {
        item = items[i];
        node = new Node(this.tree, item, parentNode);
        parentNode.children.push(node);
        if (item.children) {
          results.push(this.loadR(item.children, node));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return TreeLoad;

  })();

  window.TreeLoad = TreeLoad;

}).call(this);

//# sourceMappingURL=TreeLoad.js.map
