// Generated by CoffeeScript 1.11.1
(function() {
  var Tree;

  Tree = (function() {
    Tree.prototype.lastId = 0;

    function Tree(items, parent) {
      this.parent = parent || document.getElementsByTagName('body')[0];
      if (items) {
        this.load(items);
      }
    }

    Tree.prototype.load = function(items) {
      this.nodes = new TreeLoad(this).load(items);
      return this.root = this.nodes[0];
    };

    Tree.prototype.render = function() {
      return new NodeRender().html(this.root);
    };

    Tree.prototype.html = function() {
      this.parent.innerHTML = '';
      return this.parent.appendChild(this.render());
    };

    Tree.prototype.json = function() {
      return JSON.stringify(this.data());
    };

    Tree.prototype.data = function() {
      return [this.dataR(this.root)];
    };

    Tree.prototype.dataR = function(node) {
      var _node, data, i, len, ref;
      data = node.getData();
      if (node.children.length) {
        data.children = [];
        ref = node.children;
        for (i = 0, len = ref.length; i < len; i++) {
          _node = ref[i];
          data.children.push(this.dataR(_node));
        }
      }
      return data;
    };

    Tree.prototype.onChange = null;

    Tree.prototype.fireChangeEvent = function() {
      if (this.onChange) {
        return this.onChange();
      }
    };

    return Tree;

  })();

  window.Tree = Tree;

}).call(this);

//# sourceMappingURL=Tree.js.map
